<?php

use Blog\Comments;
use PHPUnit\Framework\TestCase;

class CommentsTest extends TestCase
{
    private $comments;

    protected function setUp(): void
    {
        $this->comments = new Comments(10, 5, 1, 'Текст комментария');
    }

    protected function tearDown(): void
    {
        parent::tearDown(); // TODO: Change the autogenerated stub
    }

    public function testComments()
    {
        $this->assertEquals('Текст комментария', $this->comments->getText());
    }

}