<?php

use Blog\Article;
use PHPUnit\Framework\TestCase;

class ArticleTest extends TestCase
{
    private $article;

    protected function setUp(): void
    {
        $this->article = new Article(10, 5, 'Описание статьи', 'Текст статьи');
    }

    protected function tearDown(): void
    {
        parent::tearDown(); // TODO: Change the autogenerated stub
    }

    public function testArticle()
    {
        $this->assertEquals('Описание статьи', $this->article->getDescription());
    }

}