<?php

use Blog\User;
use PHPUnit\Framework\TestCase;

class UserTest extends TestCase
{

    private $user;

    protected function setUp(): void
    {
        $this->user = new User(10, 'Yuriy', 'Tigunov');
    }

    protected function tearDown(): void
    {
        parent::tearDown(); // TODO: Change the autogenerated stub
    }

    public function testName()
    {
        $this->assertEquals('Yuriy', $this->user->Name());
    }


}